apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: podinfo
    spec:
      containers:
      - name: otto-ui
        image: quay.io/danielmunro/otto-ui:latest
        imagePullPolicy: IfNotPresent
        command:
        - ./podinfo
        - --port=9898
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=podinfo
        - --level=info
        - --random-delay=false
        - --random-error=false
        ports:
          - containerPort: 3000
            name: ui
        env:
          - name: API_ENDPOINT
            value: localhost
#        livenessProbe:
#          exec:
#            command:
#            - podcli
#            - check
#            - http
#            - localhost:3000/healthz
#          initialDelaySeconds: 5
#          timeoutSeconds: 5
#        readinessProbe:
#          exec:
#            command:
#            - podcli
#            - check
#            - http
#            - localhost:3000/readyz
#          initialDelaySeconds: 5
#          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
