language: node_js

services:
  - xvfb

node_js:
  - 'node'
  - 'lts/*'

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules

before_deploy:
  - docker build -t quay.io/danielmunro/otto-ui:build-$(git rev-parse --short ${TRAVIS_COMMIT}) -t quay.io/danielmunro/otto-ui:latest .
deploy:
  - provider: script
    script: bash bin/docker_push
