export const LOAD_PROFILE_USER = 'app/ProfilePage/LOAD_PROFILE_USER';
export const LOAD_PROFILE_USER_SUCCESS =
  'app/ProfilePage/LOAD_PROFILE_USER_SUCCESS';
export const LOAD_PROFILE_USER_ERROR =
  'app/ProfilePage/LOAD_PROFILE_USER_ERROR';

export const CHANGE_PROFILE_PICTURE = 'app/ProfilePage/CHANGE_PROFILE_PICTURE';

export const UPLOAD_PROFILE_PICTURE = 'app/ProfilePage/UPLOAD_PROFILE_PICTURE';
export const UPLOAD_PROFILE_PICTURE_SUCCESS =
  'app/ProfilePage/UPLOAD_PROFILE_PICTURE_SUCCESS';
export const UPLOAD_PROFILE_PICTURE_ERROR =
  'app/ProfilePage/UPLOAD_PROFILE_PICTURE_ERROR';
