export const LOAD_WHO_TO_FOLLOW = 'app/App/LOAD_WHO_TO_FOLLOW';
export const LOAD_WHO_TO_FOLLOW_SUCCESS = 'app/App/LOAD_WHO_TO_FOLLOW_SUCCESS';
export const LOAD_WHO_TO_FOLLOW_ERROR = 'app/App/LOAD_WHO_TO_FOLLOW_ERROR';
