on:
  push:
    branches:
      - main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install npm dependencies
        run: npm ci
      - name: Run setup.sh
        run: ./bin/setup.sh
      - name: Build source
        run: npm run build
  publish-image:
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
