on:
  push:
    branches:
      - main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install npm dependencies
        run: npm ci
      - name: Run setup.sh
        run: ./bin/setup.sh
#      - name: Run tests
#        run: npm test
      - name: Build source
        run: npm run build
      - name: Build image
        run: docker build -t quay.io/danielmunro/otto-ui:latest .
      - name: Push image
        run: ./bin/docker_push.sh
