on:
  push:
    branches:
      - main
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install npm dependencies
        run: npm ci
      - name: Run setup.sh
        run: ./bin/setup.sh
      - name: Build source
        run: npm run build
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_BOT_USERNAME }}
          password: ${{ secrets.QUAY_BOT_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: quay.io/danielmunro/otto-ui:latest
